[package]
name = "kondo-ui"
version = "0.1.0"
authors = ["Trent Billington <trent.h.billington@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/xi-editor/druid.git", branch = "controller", version = "0.5" }

[dependencies.kondo-lib]
path = "../kondo-lib"
version = "*"
